version: "3.6"

services:
  marketplace-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    environment:
      - DatabaseSettings__ConnectionString=Server=marketplace-db;Database=master;User=sa;Password=123@Change;MultipleActiveResultSets=true
      - DatabaseSettings__DBProvider=mssql
      - ASPNETCORE_URLS=http://+:8080
      - CORS_ORIGIN=http://marketplace-spa,http://localhost
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    depends_on:
      marketplace-db:
        condition: service_healthy
    restart: on-failure
    networks:
      - marketplace

  marketplace-db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - "SA_PASSWORD=123@Change"
      - "ACCEPT_EULA=Y"
    container_name: mssql
    ports:
      - 1433:1433
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q
        "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - marketplace
  marketplace-spa:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - API_URL_BASE=http://localhost:8080
    container_name: app
    ports:
      - 80:80
    networks:
      - marketplace
    depends_on:
      - marketplace-api

networks:
  marketplace:
